apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: single-cluster-cd-test
  annotations:
    field.cattle.io/description: Single Cluster GitRepo  Test
#    key: string
  namespace: fleet-local
#  labels:
#    key: string
spec:
  branch: master
  paths:
    - single-cluster/helm
#    - string
  repo: https://github.com/rancher/fleet-examples.git
  targets:
    - clusterSelector:
        matchExpressions:
          - key: provider.cattle.io
            operator: NotIn
            values:
              - harvester
#    - clusterGroup: string
#      clusterGroupSelector:
#        matchExpressions:
#          - key: string
#            operator: string
#            values:
#              - string
#        matchLabels:
#          key: string
#      clusterName: string
#      clusterSelector:
#        matchExpressions:
#          - key: string
#            operator: string
#            values:
#              - string
#        matchLabels:
#          key: string
#      name: string
#  caBundle: string
#  clientSecretName: string
#  forceSyncGeneration: int
#  helmSecretName: string
#  imageScanCommit:
#    authorEmail: string
#    authorName: string
#    messageTemplate: string
#  imageScanInterval: string
#  paused: boolean
#  pollingInterval: string
#  revision: string
#  serviceAccount: string
#  targetNamespace: string