apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  annotations:
    field.cattle.io/description: fleet-local-test
  creationTimestamp: '2023-03-17T16:01:22Z'
  generation: 1
  managedFields:
    - apiVersion: fleet.cattle.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:field.cattle.io/description: {}
        f:spec:
          .: {}
          f:branch: {}
          f:insecureSkipTLSVerify: {}
          f:paths: {}
          f:repo: {}
          f:targets: {}
      manager: rancher
      operation: Update
      time: '2023-03-17T16:01:22Z'
    - apiVersion: fleet.cattle.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:commit: {}
          f:conditions: {}
          f:desiredReadyClusters: {}
          f:display:
            .: {}
            f:readyBundleDeployments: {}
          f:gitJobStatus: {}
          f:lastSyncedImageScanTime: {}
          f:observedGeneration: {}
          f:readyClusters: {}
          f:resourceCounts:
            .: {}
            f:desiredReady: {}
            f:missing: {}
            f:modified: {}
            f:notReady: {}
            f:orphaned: {}
            f:ready: {}
            f:unknown: {}
            f:waitApplied: {}
          f:resources: {}
          f:summary:
            .: {}
            f:desiredReady: {}
            f:ready: {}
      manager: fleetcontroller
      operation: Update
      subresource: status
      time: '2023-03-17T16:02:26Z'
  name: fleet-local-test
  namespace: fleet-local
  resourceVersion: '466674'
  uid: a1ff16b1-a13c-4806-aba3-4b0ae40a696a
spec:
  branch: master
  insecureSkipTLSVerify: true
  paths:
    - single-cluster/helm
  repo: https://github.com/rancher/fleet-examples.git
  targets:
    - clusterSelector:
        matchExpressions:
          - key: provider.cattle.io
            operator: NotIn
            values:
              - harvester
status:
  commit: 3d38dd4054a62f355d051a9d5c34746f2f78aeca
  conditions:
    - lastUpdateTime: '2023-03-17T16:02:26Z'
      status: 'True'
      type: Ready
    - lastUpdateTime: '2023-03-17T16:12:40Z'
      status: 'True'
      type: Accepted
    - lastUpdateTime: '2023-03-17T16:01:22Z'
      status: 'True'
      type: ImageSynced
    - lastUpdateTime: '2023-03-17T16:01:23Z'
      status: 'False'
      type: Reconciling
    - lastUpdateTime: '2023-03-17T16:01:23Z'
      status: 'False'
      type: Stalled
    - lastUpdateTime: '2023-03-17T16:12:40Z'
      status: 'True'
      type: Synced
  desiredReadyClusters: 1
  display:
    readyBundleDeployments: 1/1
  gitJobStatus: Current
  lastSyncedImageScanTime: null
  observedGeneration: 1
  readyClusters: 1
  resourceCounts:
    desiredReady: 6
    missing: 0
    modified: 0
    notReady: 0
    orphaned: 0
    ready: 6
    unknown: 0
    waitApplied: 0
  resources:
    - apiVersion: apps/v1
      id: fleet-helm-example/frontend
      kind: Deployment
      name: frontend
      namespace: fleet-helm-example
      state: Ready
      type: apps.deployment
    - apiVersion: apps/v1
      id: fleet-helm-example/redis-master
      kind: Deployment
      name: redis-master
      namespace: fleet-helm-example
      state: Ready
      type: apps.deployment
    - apiVersion: apps/v1
      id: fleet-helm-example/redis-slave
      kind: Deployment
      name: redis-slave
      namespace: fleet-helm-example
      state: Ready
      type: apps.deployment
    - apiVersion: v1
      id: fleet-helm-example/frontend
      kind: Service
      name: frontend
      namespace: fleet-helm-example
      state: Ready
      type: service
    - apiVersion: v1
      id: fleet-helm-example/redis-master
      kind: Service
      name: redis-master
      namespace: fleet-helm-example
      state: Ready
      type: service
    - apiVersion: v1
      id: fleet-helm-example/redis-slave
      kind: Service
      name: redis-slave
      namespace: fleet-helm-example
      state: Ready
      type: service
  summary:
    desiredReady: 1
    ready: 1
