apiVersion: fleet.cattle.io/v1alpha1
kind: ClusterGroup
metadata:
  name: default-test-group
  annotations:
    field.cattle.io/description: group for test cluster
#    key: string
  labels:
    {}
#    key: string
  namespace: fleet-default
spec:
  selector:
    matchLabels:
      env: test
#      key: string  #use this to assign the various labels to match
    matchExpressions:
#      - key: string
#        operator: string
#        values:
#          - string