apiVersion: v1
kind: Config
clusters:
- name: "quickstart-do-custom"
  cluster:
    server: "https://rancher.192.241.157.189.sslip.io/k8s/clusters/c-m-9cj4xkdp"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2RENDQ\
      VdPZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQkdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
      kdsemRHVnVaWEl0YjNKbk1TWXdKQVlEVlFRRERCMWtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRkFNV\
      FkzT0RrNApNVFV6T1RBZUZ3MHlNekF6TVRZeE5UUTFNemxhRncwek16QXpNVE14TlRRMU16bGFNR\
      Vl4SERBYUJnTlZCQW9UCkUyUjVibUZ0YVdOc2FYTjBaVzVsY2kxdmNtY3hKakFrQmdOVkJBTU1IV\
      1I1Ym1GdGFXTnNhWE4wWlc1bGNpMWoKWVVBeE5qYzRPVGd4TlRNNU1Ga3dFd1lIS29aSXpqMENBU\
      VlJS29aSXpqMERBUWNEUWdBRS8xdHEzMmNXOEthRwpWUW5tZmw3SU9xTWV5Qmh6cTUrT3BWaDdNT\
      TB5RUdwaS9RUGd0NkdrOFZtb1JNUmQrS3NJTWsrSXcrM1kxdTFiCnQvbldFK25ZYzZOQ01FQXdEZ\
      1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWUQKVlIwT0JCWUVGT\
      k5rYVcxMEdhNnJwY3EwNVBrWEIxb2x1dE9KTUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUVJMgpIR\
      HJIbXBZckFHOGc3UTlHbTRwaEp0bnZHM1ZlU25iS3YxdXIvcmpWQWlCcm9WSVJldnRMQXFiV1haT\
      VRwTnhWCllobnpvZ0FLMkRTZDZ0TitMU0EzVVE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"

users:
- name: "quickstart-do-custom"
  user:
    token: "kubeconfig-user-gh9q55znt7:ddsx5xplzh5d4whcc4ndg7zmw5mfh2h5zspsqx4sb4zjvmdftpk5jh"


contexts:
- name: "quickstart-do-custom"
  context:
    user: "quickstart-do-custom"
    cluster: "quickstart-do-custom"

current-context: "quickstart-do-custom"
