apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: socks-demo-repo
  annotations:
    field.cattle.io/description: Git repo for socks shop repo.
#    key: string
  labels:
    {}
#    key: string
  namespace: fleet-default
spec:
  branch: master
  insecureSkipTLSVerify: false
  paths:
    - deploy/kubernetes/manifests-logging
    - deploy/kubernetes/manifests-monitoring
#    - string
  repo: https://github.com/microservices-demo/microservices-demo.git
  targets:
  # A selector used to match clusters.  The structure is the standard
    # metav1.LabelSelector format. If clusterGroupSelector or clusterGroup is specified,
    # clusterSelector will be used only to further refine the selection after
    # clusterGroupSelector and clusterGroup is evaluated.
    clusterGroup: default-test-group
    # clusterGroup: string
    clusterGroupSelector:
       matchLabels:
         env: test
        #  key: string
      #  matchExpressions:
#          - key: string
#            operator: string
#            values:
#              - string
#      clusterName: string
    clusterSelector:
      matchLabels:
        env: test
        # key: string
#        matchExpressions:
#          - key: string
#            operator: string
#            values:
#              - string
#      name: string
#  caBundle: string
#  clientSecretName: string
#  forceSyncGeneration: int
#  helmSecretName: string
#  imageScanCommit:
#    authorEmail: string
#    authorName: string
#    messageTemplate: string
#  imageScanInterval: string
#  paused: boolean
#  pollingInterval: string
#  revision: string
#  serviceAccount: string
#  targetNamespace: string