apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: socks-demo-repo
  annotations:
    field.cattle.io/description: Git repo for socks shop repo.
#    key: string
  labels:
    env: test
#    key: string
  namespace: fleet-default
spec:
  branch: main
  insecureSkipTLSVerify: false
  paths:
    - socks-microservices-demo/deploy/kubernetes/manifests-logging-cluster
    - socks-microservices-demo/deploy/kubernetes/manifests-monitoring
    - socks-microservices-demo/deploy/kubernetes/helm-chart
#    - string
  repo: https://github.com/olmofe/AltSchool_AKS_WebApps.git
  targets:
    #you can use clusterName or clusterGroup or clusterSelector/clusterGroupSeleector
    # If clusterGroupSelector or clusterGroup is specified,
    # clusterSelector will be used only to further refine the selection after
    # clusterGroupSelector and clusterGroup is evaluated.

    - clusterName: do-custom
      clusterSelector:
        matchLabels:
          env: test
#          key: string
    # specify cluster group details if that applies to your use case
    # - clusterGroup: default-test-group
    #   clusterGroupSelector:
    #     matchLabels:
    #       env: test
          # key: string
#      clusterName: string
#      name: string